FROM docker.io/nvidia/cuda:13.0.0-devel-ubuntu22.04

ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /model

RUN echo 'APT::Sandbox::User "root";' > /etc/apt/apt.conf.d/99sandbox \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
       python3 python3-dev python3-pip \
       libgomp1 libnuma1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir "vllm==0.21.0" "transformers>=4.57"
RUN pip3 install --no-cache-dir tqdm pythainlp rouge-score pandas accelerate safetensors
RUN nvcc --version

COPY entrypoint_35b.sh /model/entrypoint.sh
RUN chmod +x /model/entrypoint.sh

COPY run_vllm_35b.py run.py
COPY bge-m3/ ./bge-m3/

COPY Qwen3.6-35B-A3B-FP8/ ./Qwen3.6-35B-A3B-FP8/

CMD ["/model/entrypoint.sh"]
